max_epochs: -1
accelerator: gpu
devices: -1
reload_dataloaders_every_n_epochs: 1
log_every_n_steps: 1
val_check_interval: 1.0
num_sanity_val_steps: 0
profiler: 'simple'
fast_dev_run: False
strategy: 'ddp_find_unused_parameters_true'