_target_: src.lightning_modules.DSB

pretraining_steps: 150_000
inference_steps: 3

encoder_decoder:
  _target_: src.networks.STFTEncoderDecoder
  n_fft: 510
  hop_length: 128
  alpha: 0.25
  beta: 4.0

scheduler:
  _target_: src.lightning_modules.DSBScheduler
  epsilon: 1.0
  target: terminal
  condition_on_start: True

defaults:
  - /networks@model: dhariwal
  - /losses@loss_fn: mse
  - /optimizer: adamw
  - /lr_scheduler: constant
