_target_: src.lightning_modules.DSB

model:
  _target_: src.networks.PretrainedModel
  project_name: 'flow matching'
  experiment_id: '270125150447'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.CelebAVQ

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4

pretrained_forward_model_id: '270125150447'
pretrained_backward_model_id: '270125150447'

max_gamma: 1
min_gamma: 0.1
num_steps: 100
max_iterations: 1000
cache_max_size: 50
cache_num_iters: 10
T: 1