_target_: src.lightning_modules.DSB

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.0

effective_batch_size: 8
num_workers: 12
num_iterations: 32000
cache_max_size : 1536
cache_generator_batch_size: 256
num_cache_iterations: 30
max_DSB_iterations: 8

num_timesteps: 100
first_iteration: 'network'
target: 'flow'
max_norm: 5.0
ema_decay: 0.999