_target_: src.lightning_modules.DSB

model:
  _target_: src.networks.CelebAUNet2D

encoder_decoder:
  _target_: src.networks.CelebAVQ

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4

num_steps: 100
max_iterations: 5000
cache_max_size: 200
cache_num_iters: 10
use_pretrained_flow: False
gamma_frac: 0.1