_target_: src.lightning_modules.DSB

forward_model:
  _target_: src.networks.PretrainedModel
  experiment_id: '050325183709'
  model_keyword: 'model'

backward_model:
  _target_: src.networks.PretrainedModel
  experiment_id: '050325180742'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.01

num_steps: 100
max_iterations: 15000
cache_max_size: 5000
cache_num_iters: 20
first_iteration: 'pretrained'
target: 'flow'
gamma_frac: 1.0
added_noise: 0.001
max_norm: 1.0