_target_: src.lightning_modules.DSB

model:
  _target_: src.networks.EMNISTUNet2D

encoder_decoder:
  _target_: src.networks.EMNISTVAE

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4

max_gamma: 1
min_gamma: 1
num_steps: 100
max_iterations: 1000
cache_max_size: 100
cache_num_iters: 5
T: 0.05