_target_: src.lightning_modules.DSB

backward_model:
  _target_: src.networks.PretrainedModel
  experiment_id: '040325154454'
  model_keyword: 'model'

forward_model:
  _target_: src.networks.PretrainedModel
  experiment_id: '040325161643'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.IdentityEncoderDecoder

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4

num_steps: 100
max_iterations: 3000
cache_max_size: 2000
cache_num_iters: 10
target: 'flow'
first_iteration: 'pretrained'
max_norm: 1.0
gamma_frac: 1.0