_target_: src.lightning_modules.DSB

model:
  _target_: src.networks.EMNISTUNet
  sample_size: 16

encoder_decoder:
  _target_: src.networks.IdentityEncoderDecoder

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4

num_steps: 100
max_iterations: 3000
cache_max_size: 5000
cache_num_iters: 10