_target_: src.lightning_modules.DSB

model:
  _target_: src.networks.PretrainedModel
  experiment_id: '250225230121'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-5

num_steps: 100
max_iterations: 15000
cache_max_size: 10000
cache_num_iters: 15
use_pretrained_flow: True
gamma_frac: 0.01
added_noise: 0.001
max_norm: 1.0