_target_: src.lightning_modules.DSB

defaults:
  - /encoders@encoder_decoder: hifigan
  - /networks@model: dhariwal
  - /losses@loss_fn: mse
  - /optimizer: adamw
  - /lr_scheduler: constant

pretraining_steps: 100_000
inference_steps: 4

scheduler:
  _target_: src.lightning_modules.DSBScheduler
  epsilon: 2.0
  target: scaled_drift
  condition_on_start: False
