_target_: src.lightning_modules.FM

model:
  _target_: src.networks.PretrainedModel
  experiment_id: '010325151137'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.01

added_noise: 0.001
scheduler: 'i2'
target: 'flow'

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: 150000
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1