_target_: src.lightning_modules.FM

model:
  _target_: src.networks.DhariwalUNetFromPaper

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.1

added_noise: 0.01

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    _partial_: True
    max_lr: 5.e-4
    total_steps: 80000
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1