_target_: src.lightning_modules.FM

model:
  _target_: src.networks.PretrainedUNet2D
  model_id: 'CompVis/ldm-celebahq-256'
  subfolder: 'unet'

encoder_decoder:
  _target_: src.networks.CelebAVQ

scheduler: 
  _target_: diffusers.schedulers.DDIMScheduler
  beta_start: 0.0015
  beta_end: 0.0195
  clip_sample: False,
  beta_schedule: 'scaled_linear'

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-5