_target_: src.lightning_modules.FM

model:
  _target_: src.networks.LargeUNet

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.1

added_noise: 0.01
latent_std: 8.0
num_timesteps: 100
gamma_frac: 1.0

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    _partial_: True
    max_lr: 1.e-3
    total_steps: 50000
  monitor: 'val_loss'
  interval: 'epoch'
  frequency: 3