_target_: src.lightning_modules.FM

model:
  _target_: src.networks.MediumUNet

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4

added_noise: 0.01
latent_std: 8.0
gamma_frac: 0.001

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: True
    mode: 'min'
    factor: 0.5
    patience: 5
    cooldown: 5
  monitor: 'val_loss'
  interval: 'epoch'
  frequency: 3