_target_: src.lightning_modules.FM

model:
  _target_: src.networks.PretrainedModel
  experiment_id: '070225124621'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.CelebAVQ

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 5.e-5

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: True
    mode: 'min'
    factor: 0.5
    patience: 5
    cooldown: 3
  monitor: 'val_loss'
  interval: 'epoch'
  frequency: 1