_target_: src.lightning_modules.FM

model:
  _target_: src.networks.EMNISTUNet

encoder_decoder:
  _target_: src.networks.IdentityEncoderDecoder

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4

num_timesteps: 100
target: 'terminal'
scheduler: 'i2'

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    _partial_: True
    max_lr: 1.e-3
    total_steps: 50000
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1