_target_: src.lightning_modules.FM

model:
  _target_: src.networks.EMNISTUNet

encoder_decoder:
  _target_: src.networks.IdentityEncoderDecoder

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4

num_timesteps: 100
gamma_frac: 1.0

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: True
    mode: 'min'
    factor: 0.5
    patience: 5
    cooldown: 3
  monitor: 'val_loss'
  interval: 'epoch'
  frequency: 3