_target_: src.lightning_modules.FM

model:
  _target_: src.networks.EMNISTUNet2D

encoder_decoder:
  _target_: src.networks.EMNISTVAE

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: True
    mode: 'min'
    factor: 0.5
    patience: 5
    cooldown: 5
  monitor: 'val_loss'
  interval: 'epoch'
  frequency: 5