_target_: src.lightning_modules.FM

model:
  _target_: src.networks.CelebAUNet2D

encoder_decoder:
  _target_: src.networks.CelebAVQ

scheduler: 
  _target_: diffusers.schedulers.DDIMScheduler
  num_train_timesteps: 1000
  beta_start: 0.0015
  beta_end: 0.0195
  clip_sample: False,
  beta_schedule: 'scaled_linear'

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: True
    mode: 'min'
    factor: 0.5
    patience: 5
    cooldown: 5
  monitor: 'val_loss'
  interval: 'epoch'
  frequency: 5