_target_: src.lightning_modules.FM

model:
  _target_: src.networks.SimpleNetwork
  in_features: 2
  out_features: 2
  num_time_embeddings: 101

encoder_decoder:
  _target_: src.networks.IdentityEncoderDecoder

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4

num_timesteps: 100

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    _partial_: True
    max_lr: 1.e-3
    total_steps: 50000
  monitor: 'val_loss'
  interval: 'epoch'
  frequency: 1