_target_: src.lightning_modules.FM

model:
  _target_: src.networks.PretrainedModel
  project_name: 'flow matching'
  experiment_id: '160125205054'
  model_keyword: 'model'

encoder_decoder_id: 'stable-diffusion-3.5'

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-5

scheduler: 'ddim'
beta_start: 0.0015
beta_end: 0.0195
beta_schedule: 'scaled_linear'