_target_: src.lightning_modules.DSB

forward_model:
  _target_: src.networks.PretrainedModel
  experiment_id: '220325194817'
  model_keyword: 'model'

backward_model:
  _target_: src.networks.PretrainedModel
  experiment_id: '220325205221'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-5
  weight_decay: 0.0

num_steps: 100
max_iterations: 20000
cache_num_iters: 10
cache_max_size: 5000
first_iteration: 'network-straight'
target: 'flow'
added_noise: 0.0
max_norm: 1.0
ema_decay: 0.99