_target_: src.lightning_modules.InitDSB

model:
  # _target_: src.networks.LargeUNet1D
  # extra_in_channels: 16
  # in_channels: 64
  # out_channels: 64
  _target_: src.networks.PretrainedModel
  experiment_id: '280325100212'
  model_keyword: 'model'

encoder_decoder:
  _target_: src.networks.StableAudioEncoder
  scaling_factor: 1.0

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.0

num_timesteps: 100
target: 'flow'
ema_decay: 0.999

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    _partial_: True
    T_0: 1000
    T_mult: 2
    eta_min: 1.e-6
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1