_target_: src.lightning_modules.InitDSB

model:
  _target_: src.networks.MediumUNet1D
  in_channels: 64
  out_channels: 64

encoder_decoder:
  _target_: src.networks.StableAudioEncoder

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.0

num_timesteps: 100
target: 'flow'
ema_decay: 0.999

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ConstantLR
    _partial_: True
    factor: 1.0
    total_iters: 1
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1