_target_: src.lightning_modules.InitDSB

model:
  _target_: src.networks.MediumUNet
  in_channels: 1
  out_channels: 1

encoder_decoder:
  _target_: src.networks.PretrainedMimi

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 5.e-5
  weight_decay: 0.01

num_timesteps: 100
gamma_frac: 0.1
target: 'flow'
ema_decay: 0.999

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ConstantLR
    _partial_: True
    factor: 1.0
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1