_target_: src.lightning_modules.InitDSB

model:
  _target_: src.networks.UNet50

encoder_decoder:
  _target_: src.networks.StableDiffusionXL

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4
  weight_decay: 0.01

gamma_frac: 1.0
added_noise: 0.001
target: 'flow'
ema_decay: 0.999

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: 150000
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1