_target_: src.lightning_modules.ReFlow

model:
  _target_: src.networks.EMNISTUNet

training_backward: True

encoder_decoder:
  _target_: src.networks.IdentityEncoderDecoder

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1.e-4

num_timesteps: 100

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: 20000
  monitor: 'val_loss'
  interval: 'step'
  frequency: 1