_target_: src.lightning_modules.DSB

defaults:
  - /encoders@encoder_decoder: identity
  - /networks@model: mamba
  - /losses@loss_fn: mel
  - /optimizer: adamw
  - /lr_scheduler: constant

pretraining_steps: 100_000
inference_steps: 15

encoder_decoder:
  scaling_factor: 20

scheduler:
  _target_: src.lightning_modules.DSBScheduler
  epsilon: 1.0
  target: terminal
  condition_on_start: False
