_target_: src.lightning_modules.VAE
beta: 0.2
vae:
  _target_: diffusers.AutoencoderKL
  in_channels: 1
  out_channels: 1
  down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D','DownEncoderBlock2D','DownEncoderBlock2D']
  up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
  block_out_channels: [32, 32, 32, 64]
  sample_size: 32
  latent_channels: 1

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4
lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: True
    mode: 'min'
    factor: 0.5
    patience: 10
    min_lr: 1e-5
  monitor: 'val/loss'
  interval: 'epoch'
  frequency: 5