_target_: src.lightning_modules.DSB

defaults:
  - /encoders@encoder_decoder: identity
  - /networks@model: diffwave
  - /losses@loss_fn: l1
  - /optimizer: adamw
  - /lr_scheduler: constant

pretraining_steps: 100_000
inference_steps: 5

encoder_decoder:
  scaling_factor: 1

scheduler:
  _target_: src.lightning_modules.DSBScheduler
  epsilon: 0.05
  target: drift
  condition_on_start: False
