_target_: src.lightning_modules.PairedDSB

defaults:
  - /encoders@encoder_decoder: identity
  - /networks@model: transformer
  - /losses@loss_fn: l1
  - /optimizer: adamw
  - /lr_scheduler: constant

encoder_decoder:
  scaling_factor: 1

scheduler:
  _target_: src.lightning_modules.DSBScheduler
  epsilon: 0.05
  target: drift
  condition_on_start: False

model:
  in_channels: 1
  num_classes: 0
