_target_: src.lightning_modules.PairedDSB

defaults:
  - /encoders@encoder_decoder: identity
  - /networks@model: transformer
  - /losses@loss_fn: mse
  - /optimizer: adamw
  - /lr_scheduler: constant

encoder_decoder:
  scaling_factor: 20

scheduler:
  _target_: src.lightning_modules.DSBScheduler
  epsilon: 1.0
  target: scaled_drift
  condition_on_start: False

model:
  num_classes: 0
