- _target_: src.datasets.degradations.AddNoise
  noise_dataset:
    _target_: src.datasets.AugmentedAudioDataset

    dataset:
      _target_: src.datasets.WHAM
      split: train
    augmentations:
      - _target_: src.augmentations.ResampleAugmentation
        new_sample_rate: ${sample_rate}
      - _target_: src.augmentations.CutAndFitAugmentation
        target_length: ${train_audio_length}
        deterministic: False
      - _target_: src.augmentations.LoudnessAugmentation
        loudness_db: -20.0

  min_snr: 5
  max_snr: 5
  prob: 1.0
  deterministic: False

- _target_: src.datasets.degradations.Reverb
  mix: 0.3
  prob: 1.0
  deterministic: False
  rir_threshold: -20
  RIR_dataset:
    _target_: src.datasets.AugmentedAudioDataset

    dataset:
      _target_: src.datasets.RIR
      split: train

    augmentations:
      - _target_: src.augmentations.ResampleAugmentation
        new_sample_rate: ${sample_rate}

- _target_: src.datasets.degradations.Clip
  min_db: 3
  max_db: 6
  prob: 1.0
  deterministic: False
