- _target_: src.datasets.degradations.Reverb
  prob: 1.0
  deterministic: True
  rir_threshold: -20
  RIR_dataset:
    _target_: src.datasets.AugmentedAudioDataset

    dataset:
      _target_: src.datasets.RIR
      split: test

    augmentations:
      - _target_: src.augmentations.ResampleAugmentation
        new_sample_rate: ${sample_rate}
