unpaired_audio_metrics:
  _target_: src.callbacks.MetricsCallback
  metrics:
    # -- logging audios --
    # first log all audios in UnpairedAudioBatch...
    - _target_: src.callbacks.metrics.LogAudioMetric
      key: x0
      where: batch
      max_samples: 8
      once: True
    - _target_: src.callbacks.metrics.LogAudioMetric
      key: x1
      where: batch
      max_samples: 8
      once: True
    - _target_: src.callbacks.metrics.LogAudioMetric
      key: x1_clean
      where: batch
      max_samples: 8
      once: True
    # then log the enhanced audios in extras...
    - _target_: src.callbacks.metrics.LogAudioMetric
      key: x0_hat
      where: extras
      max_samples: 8
      once: False # log this every validation step, not just once

    # -- perceptual metrics --
    - _target_: src.callbacks.metrics.DNSMOS
      output_key: x0_hat

    # -- distortion metrics --
    - _target_: src.callbacks.metrics.SISDRi
      clean_key: x1_clean
      degraded_key: x1
      output_key: x0_hat

    - _target_: src.callbacks.metrics.WER
      clean_key: x1_clean
      output_key: x0_hat

    - _target_: src.callbacks.metrics.SRCS
      clean_key: x1_clean
      output_key: x0_hat

    - _target_: src.callbacks.metrics.FAD
      output_key: x0_hat
      real_key: x0
      
  extras:
    - _target_: src.callbacks.extras.GenerateSamplesExtra
      key: x1
      out_key: x0_hat
      direction: backward
      num_steps: 10
      encode: True
