# @package _global_
project_name: ???
task_name: ???
seed: 42
compile: False
continue_from_id: False

defaults:
  - trainer: ???
  - data: ???
  - model: ???
  - callbacks: ???
  - logger: ???
  - _self_