_target_: src.losses.WeightedLoss
losses:
  - _target_: src.losses.DriftingLoss
    temperature: 1.0
    kernel_type: laplace

  - _target_: src.losses.DriftingLoss
    temperature: 0.5
    kernel_type: laplace

  - _target_: src.losses.DriftingLoss
    temperature: 0.1
    kernel_type: laplace

  - _target_: src.losses.FeatureMatchingLoss

    feature_extractor:
      _target_: src.losses.MelSpectrogramFeatureExtractor

    loss_fn:
      _target_: src.losses.WeightedLoss

      losses:
        - _target_: src.losses.DriftingLoss
          temperature: 1.0
          kernel_type: laplace

        - _target_: src.losses.DriftingLoss
          temperature: 0.5
          kernel_type: laplace

        - _target_: src.losses.DriftingLoss
          temperature: 0.1
          kernel_type: laplace
