_target_: src.losses.WeightedLoss
losses:
  - _target_: src.losses.DriftingLoss
    temperature: 1.0
    kernel_type: laplace
    log: False
  - _target_: src.losses.DriftingLoss
    temperature: 0.5
    kernel_type: laplace
    log: False
  - _target_: src.losses.DriftingLoss
    temperature: 0.1
    kernel_type: laplace
    log: False
