_target_: src.datasets.AugmentedAudioDataset

dataset:
  _target_: src.datasets.SegmentedAudioDataset
  dataset:
    _target_: src.datasets.CHiME6
    split: train
  subset_size: 10.0

augmentations:
  - _target_: src.augmentations.ResampleAugmentation
    new_sample_rate: ${sample_rate}
  - _target_: src.augmentations.CutAndFitAugmentation
    target_length: ${train_audio_length}
    deterministic: False
  - _target_: src.augmentations.LoudnessAugmentation
    loudness_db: -20.0
