_target_: src.datasets.AugmentedAudioDataset

dataset:
  _target_: src.datasets.NewsReports
  split: train

augmentations:
  - _target_: src.augmentations.ResampleAugmentation
    new_sample_rate: ${sample_rate}
  - _target_: src.augmentations.CutAndFitAugmentation
    target_length: ${train_audio_length}
    deterministic: False
  - _target_: src.augmentations.LoudnessAugmentation
    loudness_db: -20.0
